apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodect
  labels:
    app: prodect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prodect
  template:
    metadata:
      labels:
        app: prodect
    spec:
      containers:
        - name: prodect
          image: "username/prodect:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
